USE DATABASE SNOWFLAKE_SESAS_RR8;
USE SCHEMA AUTO_IND;

-- PE001: PORCENTAJE DE “OTROS” EN MARCATIPO
CREATE OR REPLACE VIEW VW_PE001 AS
SELECT *
FROM RR8AUIDGE2016SF
WHERE MARCATIPO = '9999';

-- PE002: PÓLIZAS ACTIVAS CON PRIMADEVENGADA = 0
CREATE OR REPLACE VIEW VW_PE002 AS
SELECT EMI.*
FROM RR8AUIEMI2016SF EMI
JOIN RR8AUIDGE2016SF GE ON EMI.NUMPOLIZA = GE.NUMPOLIZA
WHERE EMI.UNIDADESEXPS > 0.0014
  AND GE.ESTATUS <> 'CANCELADO'
  AND EMI.COBERTURA <> 'OTROS'
  AND EMI.PRIMADEVENGADA = 0;

-- PE003: COBERTURAS INCOMPATIBLES LUC + RC PERSONAS
CREATE OR REPLACE VIEW VW_PE003 AS
SELECT NUMPOLIZA
FROM RR8AUIEMI2016SF
WHERE COBERTURA IN ('05', '04')
GROUP BY NUMPOLIZA
HAVING COUNT(DISTINCT COBERTURA) = 2;

-- PE004: MONTODEDUC > 0 Y MONTOPAGADO <= 0
CREATE OR REPLACE VIEW VW_PE004 AS
SELECT *
FROM RR8AUISIN2016SF
WHERE MONTODEDUC > 0
  AND MONTOPAGADO <= 0;

-- PE005: MONTODEDUC > 0 Y DEDUCIBLECTR = 0
CREATE OR REPLACE VIEW VW_PE005 AS
SELECT SINI.NUMPOLIZA, SINI.NUMEROSIN, SINI.MONTODEDUC, EMI.DEDUCIBLECTR, EMI.COBERTURA
FROM RR8AUISIN2016SF SINI
JOIN RR8AUIEMI2016SF EMI
  ON SINI.NUMPOLIZA = EMI.NUMPOLIZA
  AND SINI.COBERTURA = EMI.COBERTURA
WHERE SINI.MONTODEDUC > 0
  AND EMI.DEDUCIBLECTR = 0;

-- PE006: COBERTURA = DAÑOS MATERIALES Y CAUSA INCOMPATIBLE
CREATE OR REPLACE VIEW VW_PE006 AS
SELECT *
FROM RR8AUISIN2016SF
WHERE COBERTURA = '01'
  AND CAUSASIN IN ('02', '03', '14', '15', '16');

-- PE007: MONTOPAGADO > 0, DEDUCIBLECTR > 0, MONTODEDUC = 0
CREATE OR REPLACE VIEW VW_PE007 AS
SELECT SINI.NUMPOLIZA, SINI.NUMEROSIN, SINI.MONTOPAGADO, SINI.MONTODEDUC, EMI.DEDUCIBLECTR, SINI.COBERTURA
FROM RR8AUISIN2016SF SINI
JOIN RR8AUIEMI2016SF EMI
  ON SINI.NUMPOLIZA = EMI.NUMPOLIZA
  AND SINI.COBERTURA = EMI.COBERTURA
WHERE SINI.MONTOPAGADO > 0
  AND EMI.DEDUCIBLECTR > 0
  AND SINI.MONTODEDUC = 0;

-- PE009: SUMAASEGURADA = 0 EN CIERTAS COBERTURAS
CREATE OR REPLACE VIEW VW_PE009 AS
SELECT *
FROM RR8AUIEMI2016SF
WHERE SUMAASEGURADA = 0
  AND COBERTURA IN ('03', '04', '05', '06');

-- PE010: ROBO TOTAL CON CAUSA INVÁLIDA
CREATE OR REPLACE VIEW VW_PE010 AS
SELECT *
FROM RR8AUISIN2016SF
WHERE COBERTURA = '02'
  AND CAUSASIN NOT IN ('14', '15', '16');

-- PE011: RC BIENES CON CAUSA INVÁLIDA
CREATE OR REPLACE VIEW VW_PE011 AS
SELECT *
FROM RR8AUISIN2016SF
WHERE COBERTURA = '03'
  AND CAUSASIN NOT IN ('06', '13', '18');
